package main

import (
	"math/rand"
	"os"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
)

// generate random data for bar chart
func generateBarItems(n int) []opts.LineData {
	items := make([]opts.LineData, 0)
	for i := 0; i < n; i++ {
		items = append(items, opts.LineData{Value: rand.Intn(300)})
	}
	return items
}

func main() {
	// create a new bar instance
	bar := charts.NewLine()
	// set some global options like Title/Legend/ToolTip or anything else
	bar.SetGlobalOptions(charts.WithTitleOpts(opts.Title{
		Title:    "My first bar chart generated by go-echarts",
		Subtitle: "It's extremely easy to use, right?",
	}))

	weekDays := []string{
		"Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun",
	}

	amount := 100
	var days []string
	var n int
	for i := range amount {
		if amount > 0 {
			n = i % len(weekDays)
		}
		days = append(days, weekDays[n])
	}

	// Put data into instance
	bar.SetXAxis(days).
		AddSeries("Category A", generateBarItems(amount)).
		AddSeries("Category B", generateBarItems(amount))
	// Where the magic happens
	f, _ := os.Create("bar.html")
	bar.Render(f)
}
